name: Deploy to SharePoint On-Prem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Copy layout files to db-sp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ Missing secret: SSH_HOST"
            exit 1
          fi

          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "❌ Missing secret: SSH_USER"
            exit 1
          fi

          if [ -z "${{ secrets.SSH_PASSWORD }}" ]; then
            echo "❌ Missing secret: SSH_PASSWORD"
            exit 1
          fi

          echo "✅ All required secrets are set."

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            script: |
              echo "Moving to SharePoint layouts..."

              xcopy /E /Y "C:\Temp\CICD\*" "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\TEMPLATE\LAYOUTS\PCW\CICD\"

            echo "Deployment complete."
