name: Deploy to SharePoint On-Prem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Copy layout files to db-sp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to db-sp via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "Starting deployment..."
            # Navigate to the deployment directory
            cd "C:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\TEMPLATE\LAYOUTS\PCW\CICD"
            # Execute your deployment script or commands
            .\deploy.ps1